/**
 * eCow-logic - Bootloader
 *
 * Copyright (c) 2016 Saint-Genest Gwenael <gwen@agilack.fr>
 *
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 2 as published by the Free Software
 * Foundation. (See COPYING.GPL for details.)
 *
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
#ifndef CGI_HOME_H
#define CGI_HOME_H

const char cgi_home_content[] = 
"<html>"
  "<head>"
    "<style>"
      ".header{"
        "background-color: #222"
      "}"
      ".row{"
        "clear: both;"
        "margin-left: auto;"
        "margin-right: auto;"
        "width: 1170px;"
      "}"
      ".col-4{"
        "float: left;"
        "padding: 5px;"
        "width: 380px;"
      "}"
      ".col-12{"
        "float: left;"
        "padding: 5px;"
        "width: 1160px;"
      "}"
      ".panel{"
        "border: 1px solid #337ab7;"
        "border-radius: 5px;"
        "width: 100%;"
      "}"
      "h1{"
        "color: #9d9d9d;"
        "font-family: \"Helvetica Neue\",Helvetica,Arial,sans-serif;"
        "margin: 0;"
        "padding: 10;"
      "}"
      "h3{"
        "background-color: #337ab7;"
        "border-color: #bce8f1;"
        "color: #ffffff;"
        "margin: 0;"
        "padding: 5px 25px;"
      "}"
      "input{"
        "margin: 5px;"
      "}"
    "</style>"
    "<script type=\"text/javascript\">"
    "function online() {"
	    "var script = document.createElement('script');"
	    "script.src = \"https://cow.tools/ecl/probe-update.js\";"
	    "document.getElementsByTagName('head')[0].appendChild(script);"
    "}"
    "</script>"
  "</head>"
  "<body style=\"margin:0\">"
    "<div class=\"header\">"
      "<div class=\"row\">"
        "<h1>eCowLogic Bootloader</h1>"
      "</div>"
    "</div>"
    "<div class=\"row\" id=\"row-top\"></div>"
  
  "<div class=\"row\" id=\"row-manual\">"
   "<div class=\"col-4\">"
    "<div class=\"panel\">"
    "<h3>Firmware update</h3>"
    "<form method=\"post\" action=\"/fw\" enctype=\"multipart/form-data\">"
      "<input type=\"file\" name=\"bit\" required /><br/>"
      "<input type=\"submit\" value=\"Upload and write\"/>"
    "</form>"
    "</div>"
   "</div>"
   "<div class=\"col-4\">"
    "<div class=\"panel\">"
    "<h3>External flash update</h3>"
    "<form method=\"post\" action=\"/flash\" enctype=\"multipart/form-data\">"
      "<input type=\"file\" name=\"mem\" required /><br/>"
      "<input type=\"submit\" value=\"Upload and write\" />"
    "</form>"
    "</div>"
   "</div>"
   "<div class=\"col-4\">"
     "<div class=\"panel\">"
       "<h3>Configuration</h3>"
       "<p>Not available yet !</p>"
     "</div>"
   "</div>"
  "</div>"
  "<div class=\"row\" id=\"row-online\">"
    "<div class=\"col-12\">"
      "<div class=\"panel\">"
        "<h3>Auto-update (online)</h3>"
        "<button onclick=\"online();\" style=\"margin:10px;\">Search update</button>"
      "</div>"
    "</div>"
  "</div>"
  "</body>"
"</html>";

const char cgi_home_success[] = 
  "<html>"
    "<h1>eCowLogic Bootloader</h1>"
    "<p>Firmware update <b>SUCCESS</b>. <a href=\"/\">Return to homepage</a>.</p>"
  "</html>";

#endif
